server:
  port: 8888  # Port where your config server runs
  address: 0.0.0.0

spring:
  application:
    name: config-service  # Name of your Config Service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Booking-Container/config-data.git  # URL of the Git repository with configuration
          default-label: main  # The branch where your configuration is located (make sure this is correct)
          searchPaths: '{application}'  # This tells Spring to search for {application}.yml files in the Git repo
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.security.access.intercept.AbstractSecurityInterceptor: DEBUG
    org.springframework.cloud: DEBUG
