version: '3.8'

services:
  # Include all service definitions
  postgres-user:
    extends:
      file: compose/databases.yml
      service: postgres-user
  
  auth-service:
    extends:
      file: compose/backend.yml
      service: auth-service

include:
  - compose/databases.yml
  - compose/infrastructure.yml
  - compose/backend.yml
  - compose/frontend.yml
  - compose/tools.yml

networks:
  backend:
    driver: bridge

volumes:
  user-data:
  setting-data:
  comparison-data:
  schedule-data:
  client-data: