services:
  frontend:
    image: booking-container-frontend-admin:latest
    build: {context: ./frontend-admin}
    container_name: frontend-admin
    ports: ["4000:4000"]
    volumes: &ssl-volumes
      - ./frontend-admin/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/192.168.1.50.pem:/etc/ssl/certs/cert.pem
      - ./ssl/192.168.1.50-key.pem:/etc/ssl/private/key.pem
    depends_on: [api-gateway-service]
    networks: [backend]

  website:
    image: booking-container-frontend-website:latest
    build: {context: ./frontend-website}
    container_name: frontend-website
    ports: ["7000:7000"]
    volumes:
      - ./frontend-website/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/192.168.1.50.pem:/etc/ssl/certs/cert.pem
      - ./ssl/192.168.1.50-key.pem:/etc/ssl/private/key.pem
    depends_on: [api-gateway-service]
    networks: [backend]
