services:
  config-service:
    image: booking-container-config-service:latest
    build: {context: ./backend/config-service}
    container_name: config-service
    ports: ["8888:8888"]
    networks: [backend]
    volumes: ["./config-data/config-service.yml:/config/config-service.yml"]
    environment: {SPRING_CONFIG_LOCATION: "file:/config/config-service.yml"}

  discovery-service:
    image: booking-container-discovery-service:latest
    build: {context: ./backend/discovery-service}
    container_name: discovery-service
    ports: ["8761:8761"]
    networks: [backend]
    environment: {SPRING_APPLICATION_NAME: discovery-service}

  api-gateway-service:
    image: booking-container-api-gateway-service:latest
    build: {context: ./backend/api-gateway-service}
    container_name: api-gateway-service
    ports: ["8881:8881"]
    volumes: ["./ssl:/ssl"]
    depends_on: [discovery-service, config-service]
    environment:
      SPRING_APPLICATION_NAME: api-gateway-service
      SPRING_CONFIG_IMPORT: configserver:http://config-service:8888/
      EUREKA_SERVICE_URL: http://discovery-service:8761/eureka/
    networks: [backend]
